Add groups
Na-Nazhou/CosMaS pull request #58
Opened 2019-11-03 13:59 UTC by ShirleyWangxt

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +    if (err) console.error('Cannot get groups');
Handle the error by calling `next(err)`

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +    if (err) console.error('Cannot get courses');
same here

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +  const { module_code } = req.body;
Can be simplified the three lines to this I think?
```suggestion
  const { name, semester_name, module_code } = req.body;
```

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +      const group = {
```suggestion
      const group = data.rows[0];
```

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +    if (err) console.error('Cannot get groups');
Change `console.error` to `log.error` according to #55

2019-11-03 15:29 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +        res.redirect(`/${encodeURIComponent(semester_name)}/${encodeURIComponent(module_code)}/edit`);
Is the redirect URL correct?

2019-11-03 17:08 UTC, gary-lgy requested changes

2019-11-03 17:08 UTC, gary-lgy commented on routes/index.js
> +router.use('/groups', ensureAuthenticated, ensureProfessor, groups);
The route for groups should be nested within course. See #51 as an example.

2019-11-05 03:31 UTC, Na-Nazhou requested changes

2019-11-05 03:31 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +  log.fatal('', { semester_name, module_code, name });
```suggestion
```

2019-11-05 03:31 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +      log.error('Failed to update course');
```suggestion
      log.error('Failed to update group');
```

2019-11-05 03:31 UTC, Na-Nazhou commented on routes/groups.js
> +router.get('/:name', groups.show);
Do we need the group#show page?

2019-11-05 03:31 UTC, Na-Nazhou commented on routes/index.js
> +const { ensureAuthenticated, ensureIsAdmin, ensureProfessor } = require('../auth/middleware');
```suggestion
const { ensureAuthenticated, ensureIsAdmin, ensureProfessor } = require('../auth/middleware');
```

Can you revert the changes here? I am going to refactor the permissions

2019-11-05 04:50 UTC, Na-Nazhou requested changes
Just a minor fix

2019-11-05 04:50 UTC, Na-Nazhou commented on controllers/groups_controller.js
> +      log.error('Failed to create groups');
```suggestion
      log.error('Failed to create group');
```

2019-11-05 04:52 UTC, Na-Nazhou commented on routes/index.js
> +
```suggestion
```

2019-11-05 04:55 UTC, Na-Nazhou approved these changes

2019-11-05 04:56 UTC, merged